import{i as a,S as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const l=document.querySelector(".loader");function f(){l.style.display="flex"}function c(){l.style.display="none"}function y(i){const r="44773491-691b01ebde89d181347bf66a7";return f(),fetch(`https://pixabay.com/api/?key=${r}&q=${i}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}c();function d(i){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}const g=document.querySelector(".card-container");function b(i){const r=i.map(({webformatURL:n,largeImageURL:e,tags:t,likes:s,views:u,comments:p,downloads:h})=>`<li class="gallery-item">
                          <a class="gallery-link" href="${e}">
                              <img class="gallery-image" src="${n}" alt="${t}" />
                             
                                <ul class="gallery-text-list">
                                <li class="gallery-text-item"><h3>Likes</h3><p>${s}</p></li>
                                <li class="gallery-text-item"><h3>Views</h3><p>${u}</p></li>
                                <li class="gallery-text-item"><h3>Comments</h3><p>${p}</p></li>
                                <li class="gallery-text-item"><h3>Downloads</h3><p>${h}</p></li>
                            </ul>
                           </a>
                      </li>`).join("");g.innerHTML=r,new m(".card-container a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const S=document.querySelector(".search-form");S.addEventListener("submit",x);function x(i){i.preventDefault();const r=i.currentTarget,o=r.elements.query.value;o===""?a.warning({title:"Caution",message:"Please, enter in the photo",position:"topCenter"}):y(o).then(n=>{n.hits.length===0&&a.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),b(n.hits)}).catch(d).finally(()=>{r.reset(),c()})}
//# sourceMappingURL=commonHelpers.js.map
