import{i as a,S as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const l=document.querySelector(".loader");function p(){l.style.display="flex"}function f(){l.style.display="none"}function g(o){const r="44773491-691b01ebde89d181347bf66a7";return p(),fetch(`https://pixabay.com/api/?key=${r}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})}function y(o){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const d=document.querySelector(".card-container");function b(o){const r=o.map(({webformatURL:n,largeImageURL:e,tags:t,likes:s,views:c,comments:u,downloads:h})=>`<li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img class="gallery-image" src="${n}" alt="${t}" width="360" height="200"/>
                <ul class="gallery-text-list">
                    <li class="gallery-text-item"><h3>Likes</h3><p>${s}</p></li>
                    <li class="gallery-text-item"><h3>Views</h3><p>${c}</p></li>
                    <li class="gallery-text-item"><h3>Comments</h3><p>${u}</p></li>
                    <li class="gallery-text-item"><h3>Downloads</h3><p>${h}</p></li>
                </ul>
            </a>
        </li>`).join("");d.innerHTML=r,new m(".card-container a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const S=document.querySelector(".search-form");S.addEventListener("submit",w);function w(o){o.preventDefault();const r=o.currentTarget,i=r.elements.query.value.trim();i===""?a.warning({title:"Caution",message:"Please, enter in the photo",position:"topRight"}):g(i).then(n=>{n.hits.length===0&&a.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),b(n.hits)}).catch(y).finally(()=>{r.reset(),f()})}
//# sourceMappingURL=commonHelpers.js.map
